baseurl = "https://tuqmano.com/"
languageCode = "en-us"
title = "TuQmanoR"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "TuQmano"
    url = "/about"
[[menu.main]]
    name = "Miscellaneous"
    url = "https://tuqmano.tumblr.com/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/TuQmano"
[[menu.main]]
    name = "Talks"
    url = "https://tuqmano.com/talks"
[[menu.main]]
    name = "Research"
    url = "https://www.researchgate.net/profile/Juan_Ruiz_Nicolini"
[[menu.main]]
    name = "{polAr}"
    url = "https://electorarg.github.io/polAr/" 
[[menu.main]]
    name = "Teaching"
    url = "https://tuqmano.github.io/MetodosCiPol"     
[[menu.main]]
    name = "CV"    
    url = "https://raw.githubusercontent.com/TuQmano/tuqmano.com/master/static/data/CV_Ruiz_Nicolini.pdf"

[params]
    description = "Datos + R "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

