---
title: "Presentaciones"
output: 
 html_document:
  css: "xaringan-themer.css"
---




### 2020

 > **LatinR**: `{polAr}` - *Análisis de Datos Políicos de Argentina* 

[Abstract](https://github.com/TuQmano/latinr2020/blob/master/rmd/polAr/polar.pdf) | [`r emojifont::emoji("bar_chart")` Slides](https://www.tuqmano.com/slides/polar_slides.html#1) | [`r emojifont::emoji("package")` {polAr}](https://electorarg.github.io/polAr/) | [`r emojifont::emoji("keyboard")` blogpost](https://www.tuqmano.com/2020/05/22/empaquetar/) | [`r icon::fa("film")` Video](https://www.youtube.com/watch?v=V4xqUh6KCZs&list=PL9-E3cL2KgKkxsS3dkaFTvmh24kPpkE--&index=3).



 > **LatinR**: *MinaR los discuRsos pResidenciales* (con Camila Higa y Lucas Enrich) 

[Abstract](https://github.com/TuQmano/latinr2020/blob/master/rmd/discursos/discursos_presidenciales.pdf) | [`r emojifont::emoji("bar_chart")` Slides](https://github.com/TuQmano/latinr2020/blob/master/slides/discursos/minar_los_discursos.pdf) | [`r emojifont::emoji("keyboard")` blogpost](https://www.tuqmano.com/2020/03/11/los-discursos-de-les-presidentes/) | [`r icon::fa("film")` Video](https://www.youtube.com/watch?v=IZfNr_N7ylw&list=PL9-E3cL2KgKlNKVfiwHoGR3pHpg7x8Uzt&index=2).



 > **LatinR**: _#TuitómetroNacional: monitor de la conversación política en Argentina_ (con Camila Higa). 


[Abstract](https://github.com/TuQmano/latinr2020/blob/master/rmd/tuitometro/tuitometro.pdf) | [`r emojifont::emoji("bar_chart")` Slides](https://github.com/TuQmano/latinr2020/blob/master/slides/tuitometro/tuitometro.pdf) | [`r emojifont::emoji("keyboard")` blogpost](https://www.tuqmano.com/2019/12/20/congreso-2-0-politicos-argentinos-en-twitter/) | [`r icon::fa("film")` Video](https://www.youtube.com/watch?v=fNMwoLJ1iXQ&list=PL9-E3cL2KgKnixQ0u36DgCsGvOkOIo5D1).




### 2019

> **II Jornada de Comunicación Estratégica**: *Qué hace el público con la información?* 

[`r emojifont::emoji("bar_chart")` Slides](https://docs.google.com/presentation/d/1G7WvEvOkHzXrOomiks8ahCegBrIQXtxCtxOA9VpXmxM/edit#slide=id.p) | [`r icon::fa("film")` Video](https://youtu.be/Hga7rjnkLQA?t=1075)


> **LatinR**: *Inteligencia Electoral*  (con Juan Pablo Pilorget) 

[Abstract](https://github.com/LatinR/presentaciones-LatinR2019/blob/master/presentaciones/LatinR2019_paper_15.pdf) | [`r emojifont::emoji("bar_chart")` Slides](https://docs.google.com/presentation/d/1e78jzqMum2vjT-vQTrhoWJrroPLi8EgMPBXjoKJ7acA/edit#slide=id.p) | [`r emojifont::emoji("computer")` App](http://inteligenciaelectoral.mentacomunicacion.com.ar/) 

> **XIV Congreso Nacional de Ciencia Política**: *Herramientas interactivas para políticas y campañas electorales usando grandes volúmenes de datos. Panel: Big data & Política - Simposio Estudios Electorales* (con Juan Pablo Pilorget)  

[`r emojifont::emoji("bar_chart")` Slides](https://www.researchgate.net/publication/334573215) | [`r emojifont::emoji("computer")` App](http://socioeconomico.mentacomunicacion.com.ar/) | [`r emojifont::emoji("memo")` Conference Paper](https://www.researchgate.net/publication/334572755) 


### 2018

> **LatinR**: *Geofaceting Argentina* 

[Abstract](https://github.com/TuQmano/geofacet_ARG/blob/master/.LatinR/Geofaceting_Argentina_RuizNicolini.pdf) | [`r emojifont::emoji("bar_chart")` Slides](https://www.researchgate.net/publication/327382101_Geofaceting_Argentina_LatinR_2018) | [`r emojifont::emoji("package")` {geofaceteAR}](https://electorarg.github.io/geofaceteAR/) | [`r emojifont::emoji("keyboard")` blogpost](https://www.tuqmano.com/2020/05/22/empaquetar/).


### 2017

> **FLACSO - México (Seminario de Investigación)**: *Enchufes, espejos y tijeras: Efectos del diseño de las boletas sobre el comportamiento electora* (con Juan Dodyk)

[`r emojifont::emoji("bar_chart")` Slides](https://www.researchgate.net/publication/322642019) | [`r emojifont::emoji("memo")` Paper](https://www.researchgate.net/publication/322663247)



---


##### [`r icon::fa("globe")`](https://www.tuqmano.com/) [tuqmano.com](https://www.tuqmano.com/) 
##### [`r icon::fa("twitter")`](https://twitter.com/TuQmano)  [TuQmano](https://twitter.com/TuQmano) 
##### [`r icon::fa("github")`](https://github.com/tuqmano) [TuQmano](https://github.com/tuqmano)
